added ayush7614 info
gce-india/gce-india.github.io pull request #17
Opened 2022-08-23 19:50 UTC by Ayush7614

This PR Contains Info About Ayush7614

2022-08-23 19:50 UTC, Ayush7614 commented
cc @paramsiddharth

2022-08-24 17:54 UTC, paramsiddharth commented
Hey @Ayush7614 ! 😊 Greetings of the day. Nice to see you here as a campus expert trainee~!

I just want to make sure if you have completed the modules? If so, we can have a recruitment thread for you and add you to the organization.

2022-08-26 22:22 UTC, Ayush7614 commented
> Hey @Ayush7614 ! 😊 Greetings of the day. Nice to see you here as a campus expert trainee~!
> 
> I just want to make sure if you have completed the modules? If so, we can have a recruitment thread for you and add you to the organization.
> 
> Edit: If you haven't done the modules yet, ping me here once you're done and I'll approve the PR for tests! :)

Hey @paramsiddharth Yes I have Completed all the modules and my PR is also Merged

2022-08-27 10:24 UTC, paramsiddharth commented
@Ayush7614 Makes sense! 🤔 Sometimes there are bugs in the system due to which the campus expert profile badge takes a while to display. Could you ping me once again once the badge appears on your GitHub profile? Sorry for the inconvenience.

If it takes too long, try mentioning it to Juan.

2022-08-27 10:35 UTC, Ayush7614 commented
Sure

On Sat, Aug 27, 2022, 3:55 PM Param Siddharth ***@***.***>
wrote:

> @Ayush7614 <https://github.com/Ayush7614> Makes sense! 🤔 Sometimes there
> are bugs in the system due to which the campus expert profile badge takes a
> while to display. Could you ping me once again once the badge appears on
> your GitHub profile? Sorry for the inconvenience.
>
> If it takes too long, try mentioning it to Juan.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/gce-india/gce-india.github.io/pull/17#issuecomment-1229166577>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AP7G6LYRQVXPB5TBI6TOTVLV3HUINANCNFSM57MYBHIA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-09-02 13:32 UTC, paramsiddharth commented
@Ayush7614 Hey Ayush! 😊 Hope you're doing well. Did you get any updates? I remember when I became a campus expert we faced a similar issue and I had to report it to Juan. Either way, let me know if I can help!

2022-09-11 08:57 UTC, Ayush7614 commented
> @Ayush7614 Hey Ayush! 😊 Hope you're doing well. Did you get any updates? I remember when I became a campus expert we faced a similar issue and I had to report it to Juan. Either way, let me know if I can help!

Hey, @paramsiddharth Thank you for helping me now all things are set, my onboarding is done you can catch me on GCE's official website (https://githubcampus.expert/Ayush7614/) Can't-Wait to Join the Amazing GCE India Community, Tell me the Next Step.

2022-09-11 09:12 UTC, paramsiddharth commented on public/users/Ayush7614/info.yml
> +email: ayushknj3@gmail.com@gmail.com
I think you accidentally entered an incorrect e-mail address here (I see `@gmail.com` twice. Please fix that. :)

2022-09-11 09:15 UTC, paramsiddharth requested changes
> > @Ayush7614 Hey Ayush! 😊 Hope you're doing well. Did you get any updates? I remember when I became a campus expert we faced a similar issue and I had to report it to Juan. Either way, let me know if I can help!
> 
> Hey, @paramsiddharth Thank you for helping me now all things are set, my onboarding is done you can catch me on GCE's official website (https://githubcampus.expert/Ayush7614/) Can't-Wait to Join the Amazing GCE India Community, Tell me the Next Step.

@Ayush7614 Hey Ayush, that's perfect! 😊 I just need you to complete a few more steps and you'll be in!
- [ ] Accept the invitation to the organization that I'm sending you in a few minutes.
- [ ] Fix the typo I pointed out in the PR review I mentioned above. After that, you can merge the PR once the tests pass.
- [ ] Keep an eye for the thread recruitment thread I create for you once you have accepted the organization invitation.

Welcome to the community, Ayush! 😊❤ So happy to have you here.

2022-09-11 09:29 UTC, paramsiddharth commented on public/users/Ayush7614/info.yml
> +college: ABES ENGINEERING COLLEGE GHAZIABAD UP INDIA
You're using the wrong key here. It should be `university`, not `college`. :)

2022-09-11 09:30 UTC, paramsiddharth requested changes
I just noticed another error you made which is why the tests were failing. Please check!

2022-09-11 09:36 UTC, Ayush7614 commented
> I just noticed another error you made which is why the tests were failing. Please check!

Done

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Brittle

2022-09-11 09:41 UTC, paramsiddharth approved these changes
@Ayush7614 Excellent, Ayush! 😊 Go ahead and merge your PR once the tests pass and then head over to the issue I created for you in the affairs section: [affairs#33](https://github.com/gce-india/affairs/issues/33)

2022-09-11 09:45 UTC, merged

2022-09-11 09:46 UTC, Ayush7614 commented
> @Ayush7614 Excellent, Ayush! 😊 Go ahead and merge your PR once the tests pass and then head over to the issue I created for you in the affairs section: [affairs#33](https://github.com/gce-india/affairs/issues/33)

Thanks, @paramsiddharth helping me throughout the process

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome